- name: Configure VM for Serving DNS
  hosts: nameservers
  become: true
  vars:
  tasks:
    - name: Set Hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
    - name: Install & Configure bind9
      block:
        - name: "Update packages and install 'bind9'"
          ansible.builtin.apt:
            update_cache: true
            pkg:
              - bind9
              - bind9utils
              - bind9-doc
            state: present
        - name: "Copy named.conf.options"
          ansible.builtin.copy:
            src: ../files/named.conf.options
            dest: /etc/bind/named.conf.options
            mode: '644'
            owner: root
            group: bind

        - name: "Copy named.conf.local"
          ansible.builtin.copy:
            src: ../files/named.conf.local
            dest: /etc/bind/named.conf.local
            mode: '644'
            owner: root
            group: bind

        - name: "Copy Zones"
          ansible.builtin.copy:
            src: ../files/zones
            dest: /etc/bind/
            mode: '644'
            owner: root
            group: bind

        - name: "Restart BIND Service"
          ansible.builtin.systemd:
            name: bind9
            state: restarted
            enabled: true

    # - name: Restarting Server
    #   ansible.builtin.reboot:
    #     pre_reboot_delay: 1
