- name: Configure kubernetes metrics
  become: true
  become_user: k8sadmin
  block:
    - name: Install kubernetes metrics server
      ansible.builtin.command: kubectl apply -f https://raw.githubusercontent.com/techiescamp/kubeadm-scripts/main/manifests/metrics-server.yaml
