- name: Initialise VM
  block:
    - name: Remove packer user
      ansible.builtin.user:
        name: packer
        state: absent
    - name: Set Hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
