- name: Configure Master Node
  become: true
  block:
    - name: Initialize the cluster
      ansible.builtin.shell: |
        export KUBECONFIG='/etc/kubernetes/admin.conf'
        sudo kubeadm init --pod-network-cidr=10.0.0.0/16 --cri-socket=/var/run/crio/crio.sock --ignore-preflight-errors Swap >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: Create .kube directory
      ansible.builtin.file:
        path: /home/k8sadmin/.kube
        state: directory
        mode: "0755"
      become: true
      become_user: k8sadmin

    - name: Copy admin.conf
      ansible.builtin.copy:
        remote_src: true
        src: "/etc/kubernetes/admin.conf"
        dest: "/home/k8sadmin/.kube/config"
        owner: k8sadmin

    - name: Install calico Pod network
      become: true
      become_user: k8sadmin
      ansible.builtin.shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      args:
        chdir: $HOME

    - name: Get join token
      become: true
      become_user: k8sadmin
      ansible.builtin.shell: sudo kubeadm token create --print-join-command
      register: kubernetes_join_command

    - name: Copy join command to local file
      become: true
      delegate_to: localhost
      ansible.builtin.copy:
        content: "{{ kubernetes_join_command.stdout_lines[0] }}"
        dest: "/tmp/kubernetes_join_command"
        mode: "0777"
